ARG ROS_DISTRO
FROM ros:${ROS_DISTRO}

RUN apt update 
RUN apt install ros-humble-joy-teleop ros-humble-teleop-twist-joy -y

CMD [ "ros2", "launch", "teleop_twist_joy", "teleop-launch.py", "joy_vel:='commands/velocity'" ]