ARG ROS_DISTRO
FROM ros:${ROS_DISTRO}

ENV COLCON_WS=/root/colcon_ws
ENV COLCON_WS_SRC=/root/colcon_ws/src
ENV PYTHONWARNINGS="ignore:setup.py install is deprecated::setuptools.command.install"

ENV DEBIAN_FRONTEND noninteractive

RUN apt update \ 
    && apt install ros-${ROS_DISTRO}-kobuki-ros-interfaces ros-${ROS_DISTRO}-kobuki-velocity-smoother -y

WORKDIR ${COLCON_WS_SRC}
RUN git clone https://github.com/kobuki-base/kobuki_core.git\
    && git clone https://github.com/kobuki-base/kobuki_ros.git\
    && git clone https://github.com/kobuki-base/cmd_vel_mux.git\
    && git clone https://github.com/stonier/ecl_core.git\
    && git clone https://github.com/stonier/ecl_lite.git

# could also be installed via apt-get install ros-${ROS_DISTRO}-sophus and changing the files in the PR
RUN git clone https://github.com/clalancette/sophus.git -b clalancette/fix-compiler-error

WORKDIR ${COLCON_WS}
RUN . /opt/ros/${ROS_DISTRO}/setup.sh\
    && apt update \
    && rosdep install -i --from-path src --rosdistro ${ROS_DISTRO} -y \
    && colcon build --symlink-install --executor sequential