ARG ROS_DISTRO
FROM brean/kobuki-base:${ROS_DISTRO}_arm64_001

# see https://github.com/helloric/docker-env-kobuki/blob/main/Dockerfile

ENV COLCON_WS=/root/colcon_ws
ENV COLCON_WS_SRC=/root/colcon_ws/src

COPY ./ricbot_description ${COLCON_WS_SRC}/ricbot_description
COPY ./ricbot_bringup ${COLCON_WS_SRC}/ricbot_bringup
COPY ./ricbot_navigation ${COLCON_WS_SRC}/ricbot_navigation

RUN cd ${COLCON_WS}\
    && . /opt/ros/${ROS_DISTRO}/setup.sh\
    && colcon build --packages-select ricbot_description ricbot_bringup

CMD ["ros2", "launch", "ricbot_bringup", "ricbot_robot.launch.py"]
