ARG ROS_DISTRO=jazzy

FROM ros:${ROS_DISTRO}

ENV DEBIAN_FRONTEND=noninteractive

# Note that this is not needed with ROS 2 jazzy anymore
ENV PYTHONWARNINGS="ignore:setup.py install is deprecated::setuptools.command.install"

# Install required packages
RUN apt update \
    && apt install -y \
        python3-colcon-common-extensions \
        python3-evdev \
    && rm -rf /var/lib/apt/lists/*

# Install ds4drv
WORKDIR /opt
RUN git clone https://github.com/naoki-mizuno/ds4drv --branch devel \
    && cd ds4drv \
    && python3 setup.py install

# Build workspace
WORKDIR /opt/underlay_ws
RUN mkdir src \
    && cd src \
    && git clone https://github.com/naoki-mizuno/ds4_driver \
        --branch ${ROS_DISTRO}-devel
RUN bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && colcon build"

COPY ./docker/entrypoint-ds4.bash /entrypoint.bash
RUN chmod +x /entrypoint.bash
ENTRYPOINT ["/entrypoint.bash"]

COPY docker/ds4_twist.launch.xml /opt/underlay_ws/install/ds4_driver/share/ds4_driver/launch/ds4_twist.launch.xml

CMD [ "ros2", "launch", "ds4_driver", "ds4_twist.launch.xml"]
