ARG ROS_DISTRO=humble
FROM ros:${ROS_DISTRO}

RUN apt update 
RUN apt install ros-humble-teleop-twist-keyboard -y

CMD [ "ros2", "run", "teleop_twist_keyboard", "teleop_twist_keyboard", "--ros-args", "--remap", "cmd_vel:=commands/velocity" ]