ARG ROS_DISTRO
FROM ros:${ROS_DISTRO}

ENV COLCON_WS=/root/colcon_ws
ENV COLCON_WS_SRC=/root/colcon_ws/src
ENV PYTHONWARNINGS="ignore:setup.py install is deprecated::setuptools.command.install"

ENV DEBIAN_FRONTEND noninteractive

WORKDIR ${COLCON_WS_SRC}

# ROS 2 basic navigation and driver
RUN apt-get update -qq \
    && apt-get install -y \
    git \
    ros-${ROS_DISTRO}-xacro \
    ros-${ROS_DISTRO}-ecl-build \
    ros-${ROS_DISTRO}-kobuki-velocity-smoother \
    ros-${ROS_DISTRO}-joint-state-publisher \
    ros-${ROS_DISTRO}-rplidar-ros \
    ros-${ROS_DISTRO}-realsense2-camera \
    ros-${ROS_DISTRO}-nav2-amcl \
    ros-${ROS_DISTRO}-nav2-dwb-controller \
    python3-colcon-common-extensions \
    && rm -rf /var/lib/apt/lists/*

# perception and vision
RUN apt-get update -qq \
    && apt-get install -y \
    ros-${ROS_DISTRO}-perception \
    ros-${ROS_DISTRO}-vision-opencv \
    && rm -rf /var/lib/apt/lists/*

WORKDIR ${COLCON_WS}

COPY ./docker/entrypoint.bash /ros_entrypoint.bash
RUN chmod +x /ros_entrypoint.bash
ENTRYPOINT ["/ros_entrypoint.bash"]

RUN cd ${COLCON_WS_SRC}\
    && git clone https://github.com/clalancette/sophus.git -b clalancette/fix-compiler-error\
    && git clone https://github.com/kobuki-base/kobuki_ros.git\
    && git clone https://github.com/kobuki-base/kobuki_core.git\
    && git clone https://github.com/kobuki-base/kobuki_ros_interfaces.git\
    && git clone https://github.com/kobuki-base/cmd_vel_mux.git \
    && git clone https://github.com/stonier/ecl_lite.git\
    && git clone https://github.com/stonier/ecl_core.git

RUN cd ${COLCON_WS}\
    && . /opt/ros/${ROS_DISTRO}/setup.sh\
    && apt-get update -qq \
    && rosdep install -i --from-path src --rosdistro humble -y \
    && rm -rf /var/lib/apt/lists/*\
    && colcon build

COPY ./ricbot_description ${COLCON_WS_SRC}/ricbot_description
COPY ./ricbot_bringup ${COLCON_WS_SRC}/ricbot_bringup
COPY ./ricbot_navigation ${COLCON_WS_SRC}/ricbot_navigation

RUN cd ${COLCON_WS}\
    && . /opt/ros/${ROS_DISTRO}/setup.sh\
    && colcon build --packages-select ricbot_description ricbot_bringup