ARG ROS_DISTRO=humble
FROM brean/kobuki-base:${ROS_DISTRO}_arm64_001

# see https://github.com/helloric/docker-env-kobuki/blob/main/Dockerfile

# Workaround as the certificates expired on 2025-06-01
RUN rm /etc/apt/sources.list.d/ros2-latest.list \
  && rm /usr/share/keyrings/ros2-latest-archive-keyring.gpg

RUN apt-get update \
  && apt-get install -y ca-certificates curl \
  && rm -rf /var/lib/apt/lists/*

RUN export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') ;\
    curl -L -s -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" \
    && apt-get update \
    && apt-get install /tmp/ros2-apt-source.deb \
    && rm -f /tmp/ros2-apt-source.deb \
    && rm -rf /var/lib/apt/lists/*
# Workaround ends here

# Install required packages
RUN apt update \
    && apt install -y \
        ros-${ROS_DISTRO}-rplidar-ros \
        ros-${ROS_DISTRO}-robot-state-publisher \
    && rm -rf /var/lib/apt/lists/*

ENV COLCON_WS=/root/colcon_ws
ENV COLCON_WS_SRC=/root/colcon_ws/src

COPY ./docker/entrypoint.bash /entrypoint.bash
RUN chmod +x /entrypoint.bash
ENTRYPOINT ["/entrypoint.bash"]

COPY ./ricbot_description ${COLCON_WS_SRC}/ricbot_description
COPY ./ricbot_bringup ${COLCON_WS_SRC}/ricbot_bringup
COPY ./ricbot_navigation ${COLCON_WS_SRC}/ricbot_navigation

RUN cd ${COLCON_WS}\
    && . /opt/ros/${ROS_DISTRO}/setup.sh\
    && colcon build --packages-select ricbot_description ricbot_bringup

CMD ["ros2", "launch", "ricbot_bringup", "ricbot_robot.launch.py"]
